[kibana] temporarily disable readinessProbe
this is just to avoid constant pods killed during tests

diff --git a/kibana/templates/deployment.yaml b/kibana/templates/deployment.yaml
--- a/kibana/templates/deployment.yaml
+++ b/kibana/templates/deployment.yaml
@@ -110,37 +110,37 @@ spec:
         envFrom:
 {{ toYaml .Values.envFrom | indent 10 }}
 {{- end }}
-        readinessProbe:
-{{ toYaml .Values.readinessProbe | indent 10 }}
-          exec:
-            command:
-              - bash
-              - -c
-              - |
-                #!/usr/bin/env bash -e
+#         readinessProbe:
+# {{ toYaml .Values.readinessProbe | indent 10 }}
+#           exec:
+#             command:
+#               - bash
+#               - -c
+#               - |
+#                 #!/usr/bin/env bash -e
 
-                # Disable nss cache to avoid filling dentry cache when calling curl
-                # This is required with Kibana Docker using nss < 3.52
-                export NSS_SDB_USE_CACHE=no
+#                 # Disable nss cache to avoid filling dentry cache when calling curl
+#                 # This is required with Kibana Docker using nss < 3.52
+#                 export NSS_SDB_USE_CACHE=no
 
-                http () {
-                    local path="${1}"
-                    set -- -XGET -s --fail -L
+#                 http () {
+#                     local path="${1}"
+#                     set -- -XGET -s --fail -L
 
-                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
-                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
-                    fi
+#                     if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
+#                       set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
+#                     fi
 
-                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "{{ .Values.protocol }}://localhost:{{ .Values.httpPort }}${path}")
-                    if [[ "${STATUS}" -eq 200 ]]; then
-                      exit 0
-                    fi
+#                     STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "{{ .Values.protocol }}://localhost:{{ .Values.httpPort }}${path}")
+#                     if [[ "${STATUS}" -eq 200 ]]; then
+#                       exit 0
+#                     fi
 
-                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
-                    exit 1
-                }
+#                     echo "Error: Got HTTP code ${STATUS} but expected a 200"
+#                     exit 1
+#                 }
 
-                http "{{ .Values.healthCheckPath }}"
+#                 http "{{ .Values.healthCheckPath }}"
         ports:
         - containerPort: {{ .Values.httpPort }}
 {{- if .Values.lifecycle }}
